version: '2.1'

services:
  renova:
    image: renova
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 2500:2500
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js